apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cam-server.fullname" . }}
  labels:
    {{- include "cam-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cam-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cam-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.ovpn.enabled }}
      volumes:
        - name: vpn-config
          secret:
            secretName: {{ .Values.ovpn.secretName }}
            items:
                - key: client.ovpn
                  path: client.ovpn
                - key: auth.txt
                  path: auth.txt
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "cam-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /health-check
              port: http
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- if or (ne .Values.resources.limits.cpu "") (ne .Values.resources.limits.memory "") }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{ else }}
            {}
            {{- end }}
          env:
            {{- include "helpers.list-env-variables" . | indent 12 }}
          {{- if .Values.ovpn.enabled }}
          command: ["sh", "-c", "./run.sh --path=/etc/openvpn"]
          {{ else }}
          command: ["sh", "-c", "./run.sh"]
          {{- end }}
          {{- if .Values.ovpn.enabled }}
          volumeMounts:
            - name: vpn-config
              mountPath: /etc/openvpn
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
